version: "3.3"

services:

  posts:
    build:
      context: .
    image: moleculer-sequelize-file-load
    env_file: docker-compose.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --local-infile=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: posts
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:

volumes:
  data:
